jenkins:
  systemMessage: "LMCache RBLN CI Demo"
  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              id: "GITHUB_PAT"
              secret: "${GITHUB_PAT}"
              description: "GitHub PAT for opendataio/LMCache"
